//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAdaptor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public Audit()
        {
            this.Findings = new HashSet<Finding>();
            this.AuditWellSites = new HashSet<AuditWellSite>();
        }
    
        public int AuditID { get; set; }
        public Nullable<int> QuestionaireID { get; set; }
        public Nullable<int> TempleteID { get; set; }
        public string AuditTypeCode { get; set; }
        public string AuditStatusCode { get; set; }
        public string AuditPartycode { get; set; }
        public Nullable<int> psLocID { get; set; }
        public Nullable<int> FacilityName { get; set; }
        public string AuditName { get; set; }
        public Nullable<int> Employees { get; set; }
        public Nullable<int> DataEntryUserID { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Comments { get; set; }
        public string FnLegalOpinionLetterDocID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string FiltermodifiedBy { get; set; }
        public Nullable<System.DateTime> FilterModifiedDate { get; set; }
        public string SubmitedBy { get; set; }
        public Nullable<System.DateTime> SubmitedDate { get; set; }
        public Nullable<bool> DesktopAudit { get; set; }
        public Nullable<int> CEMUserID { get; set; }
        public Nullable<int> BusinessLiaisonUserID { get; set; }
    
        public virtual ICollection<Finding> Findings { get; set; }
        public virtual ICollection<AuditWellSite> AuditWellSites { get; set; }
    }
}
