//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAdaptor
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditWellSite
    {
        public int AuditSiteWellID { get; set; }
        public Nullable<int> WellID { get; set; }
        public Nullable<int> OperatorID { get; set; }
        public Nullable<int> SiteSettingID { get; set; }
        public Nullable<int> AuditId { get; set; }
        public string WellStatus { get; set; }
        public Nullable<System.DateTime> SiteVisitDate { get; set; }
        public Nullable<bool> IsWellPluggedandAbandoned { get; set; }
        public string GeneralNotes { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> SiteVisitedDate { get; set; }
    
        public virtual Audit Audit { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual SiteSetting SiteSetting { get; set; }
        public virtual Well Well { get; set; }
    }
}
