//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAdaptor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operator
    {
        public Operator()
        {
            this.AuditWellSites = new HashSet<AuditWellSite>();
        }
    
        public int OperatorID { get; set; }
        public Nullable<int> OperatorIdNbr { get; set; }
        public string OperatorName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<AuditWellSite> AuditWellSites { get; set; }
    }
}
