//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAdaptor
{
    using System;
    using System.Collections.Generic;
    
    public partial class WellName
    {
        public WellName()
        {
            this.Wells = new HashSet<Well>();
        }
    
        public int WellNameID { get; set; }
        public string WellName1 { get; set; }
        public string WellNameDesc { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ICollection<Well> Wells { get; set; }
    }
}
