//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAdaptor
{
    using System;
    using System.Collections.Generic;
    
    public partial class Well
    {
        public Well()
        {
            this.AuditWellSites = new HashSet<AuditWellSite>();
        }
    
        public int WellID { get; set; }
        public Nullable<int> WellNameID { get; set; }
        public Nullable<int> WellTypeID { get; set; }
        public string WellSerialID { get; set; }
        public string WellMbr { get; set; }
        public string SectionTownshipRange { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string WellDescription { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual WellName WellName { get; set; }
        public virtual WellType WellType { get; set; }
        public virtual ICollection<AuditWellSite> AuditWellSites { get; set; }
    }
}
